### ISSUE TITLE
Waterfall chart not working

### ISSUE THREAD

**Issue by khraibani** [gevgeny/angular2-highcharts#128]
is waterfall chart supported?

error stack below

VM12331:54 Error: Highcharts error #17: www.highcharts.com/errors/17
    at a.error (eval at 128 (http://localhost:8080/js/app.js:62:1), <anonymous>:10:47)
    at a.Chart.initSeries (eval at 128 (http://localhost:8080/js/app.js:62:1), <anonymous>:238:152)
    at eval (eval at 128 (http://localhost:8080/js/app.js:62:1), <anonymous>:261:244)
    at Array.forEach (native)
    at a.each (eval at 128 (http://localhost:8080/js/app.js:62:1), <anonymous>:26:447)
    at a.Chart.firstRender (eval at 128 (http://localhost:8080/js/app.js:62:1), <anonymous>:261:215)
    at a.Chart.init (eval at 128 (http://localhost:8080/js/app.js:62:1), <anonymous>:238:45)
    at a.Chart.getArgs (eval at 128 (http://localhost:8080/js/app.js:62:1), <anonymous>:237:56)
    at a.Chart (eval at 128 (http://localhost:8080/js/app.js:62:1), <anonymous>:236:381)
    at Object.initChart (eval at 485 (http://localhost:8080/js/app.js:474:1), <anonymous>:14:12)
    at ChartComponent.init (eval at 478 (http://localhost:8080/js/app.js:418:1), <anonymous>:36:38)
    at ChartComponent.set [as options] (eval at 478 (http://localhost:8080/js/app.js:418:1), <anonymous>:28:18)
    at Wrapper_ChartComponent.check_options (/ChartModule/ChartComponent/wrapper.ngfactory.js:39:26)
    at CompiledTemplate.proxyViewClass.View_WaterfallComponent0.detectChangesInternal (/VisualizationModule/WaterfallComponent/component.ngfactory.js:47:28)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:2497:1), <anonymous>:298:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:2497:1), <anonymous>:391:44)
    at CompiledTemplate.proxyViewClass.View_DashboardComponent0.detectChangesInternal (/AppModule/DashboardComponent/component.ngfactory.js:766:21)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:2497:1), <anonymous>:298:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:2497:1), <anonymous>:391:44)
    at CompiledTemplate.proxyViewClass.View_DashboardComponent_Host0.detectChangesInternal (/AppModule/DashboardComponent/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:2497:1), <anonymous>:298:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:2497:1), <anonymous>:391:44)
    at ViewContainer.detectChangesInNestedViews (eval at <anonymous> (http://localhost:8080/js/vendor.js:2504:1), <anonymous>:49:37)
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:68:14)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:2497:1), <anonymous>:298:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:2497:1), <anonymous>:391:44)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:2497:1), <anonymous>:298:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:2497:1), <anonymous>:391:44)
    at ViewRef_.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:1605:1), <anonymous>:136:20)
    at eval (eval at <anonymous> (http://localhost:8080/js/vendor.js:931:1), <anonymous>:463:84)
    at Array.forEach (native)
    at ApplicationRef_.tick (eval at <anonymous> (http://localhost:8080/js/vendor.js:931:1), <anonymous>:463:38)
    at eval (eval at <anonymous> (http://localhost:8080/js/vendor.js:931:1), <anonymous>:404:105)
    at ZoneDelegate.invoke (eval at 834 (http://localhost:8080/js/polyfills.js:766:1), <anonymous>:232:26)
    at Object.onInvoke (eval at <anonymous> (http://localhost:8080/js/vendor.js:1036:1), <anonymous>:238:37)
    at ZoneDelegate.invoke (eval at 834 (http://localhost:8080/js/polyfills.js:766:1), <anonymous>:231:32)
    at Zone.run (eval at 834 (http://localhost:8080/js/polyfills.js:766:1), <anonymous>:114:43)
    at NgZone.run (eval at <anonymous> (http://localhost:8080/js/vendor.js:1036:1), <anonymous>:128:62)
    at Object.next (eval at <anonymous> (http://localhost:8080/js/vendor.js:931:1), <anonymous>:404:81)
    at SafeSubscriber.schedulerFn [as _next] (eval at <anonymous> (http://localhost:8080/js/vendor.js:980:1), <anonymous>:89:52)
    at SafeSubscriber.__tryOrUnsub (eval at <anonymous> (http://localhost:8080/js/vendor.js:20:1), <anonymous>:223:16)
    at SafeSubscriber.next (eval at <anonymous> (http://localhost:8080/js/vendor.js:20:1), <anonymous>:172:22)
    at Subscriber._next (eval at <anonymous> (http://localhost:8080/js/vendor.js:20:1), <anonymous>:125:26)
    at Subscriber.next (eval at <anonymous> (http://localhost:8080/js/vendor.js:20:1), <anonymous>:89:18)
    at EventEmitter.Subject.next (eval at <anonymous> (http://localhost:8080/js/vendor.js:64:1), <anonymous>:55:25)
    at EventEmitter.emit (eval at <anonymous> (http://localhost:8080/js/vendor.js:980:1), <anonymous>:81:76)
    at NgZone.checkStable (eval at <anonymous> (http://localhost:8080/js/vendor.js:1036:1), <anonymous>:206:40)
    at NgZone.onLeave (eval at <anonymous> (http://localhost:8080/js/vendor.js:1036:1), <anonymous>:273:14)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:8080/js/vendor.js:1036:1), <anonymous>:232:27)
    at ZoneDelegate.invokeTask (eval at 834 (http://localhost:8080/js/polyfills.js:766:1), <anonymous>:264:40)
    at Zone.runTask (eval at 834 (http://localhost:8080/js/polyfills.js:766:1), <anonymous>:154:47)

**Comment by gevgeny** [comment]
Everything supported if it is supported by Highcharts. Just plug appropriate module. See the readme
