### ISSUE TITLE
Error: Unexpected value 'ChartModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by michael-brade** [gevgeny/angular2-highcharts#75]
I am using `angular2-highcharts` with Ionic 2 RC.0. But I am getting the following error:

```
[12:52:35]  ngc error: Error: Unexpected value 'ChartModule' imported by the module 'AppModule'
    at node_modules/@angular/compiler/bundles/compiler.umd.js:14113:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:14096:46)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:12937:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (node_modules/@angular/compiler/bundles/compiler.umd.js:12936:21)
    at CodeGenerator.codegen (node_modules/@angular/compiler-cli/src/codegen.js:105:47)
```

I am using it like this:

```
// app.module.js
import { ChartModule } from 'angular2-highcharts';

@NgModule({
  imports: [
    ...
    ChartModule, 
    ...
  ],
  ...
})
export class AppModule { }
```

Error happens when I do `npm run build`. Any ideas?

**Comment by michael-brade** [comment]
BTW, `npm run watch` gives me:

```
[13:13:50]  Error: Module node_modules/angular2-highcharts/index.js does not export ChartModule (imported by .tmp/app/app.module.js)
    at Module.trace (node_modules/rollup/dist/rollup.js:7677:29)
    at ModuleScope.findDeclaration (node_modules/rollup/dist/rollup.js:7300:22)
    at Scope.findDeclaration (node_modules/rollup/dist/rollup.js:5351:39)
    at Identifier.bind (node_modules/rollup/dist/rollup.js:6489:29)
    at node_modules/rollup/dist/rollup.js:5151:50
    at ArrayExpression.eachChild (node_modules/rollup/dist/rollup.js:5165:19)
    at ArrayExpression.bind (node_modules/rollup/dist/rollup.js:5151:7)
    at node_modules/rollup/dist/rollup.js:5151:50
    at Node.eachChild (node_modules/rollup/dist/rollup.js:5168:5)
    at Node.bind (node_modules/rollup/dist/rollup.js:5151:7)
```

**Comment by fank** [comment]
Works fine:

```
$ npm run watch

> angular2-highcharts@0.3.2 watch /home/mfkinder/Desktop/angular2-highcharts
> tsc -w

1:29:23 PM - Compilation complete. Watching for file changes.
```

**Comment by michael-brade** [comment]
hm. Are you using this with Ionic 2?

**Comment by fank** [comment]
no, default angular2.

**Comment by michael-brade** [comment]
ok, then I think there is something that doesn't play nicely with the current Ionic 2 release candidate. It has its own build and watch scripts under `@ionic/app-scripts`.

**Comment by singhjusraj** [comment]
This happens when using AoT compilation in Angular 2.

When I try to run ngc, it errors out as following:

`Error: Unexpected value 'ChartModule' imported by the module 'ReportsModule'
    at C:\Users\sukhdeep\Documents\Angular\gd_dev_server\node_modules\@angular\compiler\bundles\compiler.umd.js:14109:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\sukhdeep\Documents\Angular\gd_dev_server\node_modules\@angular\compiler\bundles\compiler.umd.js:14094:46)
`

I believe it has resemblance to the issue #70 

the metadata.json files are missing from the library which are required by ngc.
I'm using default angular 2, no ionic here.

Can those missing files be added soon?
Thanks.

**Comment by fank** [comment]
Sure, but i realy don't how they should looks like or how they will be generated.

**Comment by singhjusraj** [comment]
![node_modules](https://cloud.githubusercontent.com/assets/3210920/18962238/006e5814-863e-11e6-82c1-6ad1ee7d62bf.PNG)

every core angular package has an index.metadata.json file which is utilized by ngc during compilation.

If you reference to this issue https://github.com/angular/angular/issues/11262

They say that these metadata files are auto-generated by ngc.
So if you try to compile this library with ngc, I believe the metadata file will be autogenerated.

**Comment by fank** [comment]
@Sukh9212 yea it does PR is on the way
